### ISSUE TITLE
Unable to rate talks from favourites "view"

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#66] opened 2023-10-10 09:59 UTC
The "favourites" page doesn't show the rating button, which prevents users to directly rate the favourited talks! 

<img width="893" alt="image" src="https://github.com/voxxrin/voxxrin3/assets/179457/c446102d-7849-47a1-aa98-65345efd5749">

**Comment by fcamblor** [comment] 2023-10-10 10:31
Closing as duplicate of #43

**Closed by fcamblor** 2023-10-10 10:31 UTC
